name: Python package

on:
  pull_request:
    branches:
      - tb_plugin

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    # You can test your matrix by printing the current Python version
    - name: Install Pytorch
      run: |
        python -c "import sys; print(sys.version)"
        pip install numpy
        pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
        python -c "import torch; print(torch.__version__); from torch.autograd import kineto_available; print(kineto_available())"
